language: python
python:
- '3.4'
- '3.5'
- '3.7'
cache:
  pip: false
deploy:
  provider: pypi
  user: iyzico
  password:
    secure: JjLYGkbmU8OMv+dGhWH0ZkrgtRPR/8vqYwWGWhJ3bOwZeLVte994WBlcBqL3IgNjA4aUd9bw55BERe2kUHKGx83z7NGl3e+0I1WpSHE8WVM204MQKSxT6LCbfNhRk9uO+cXzMgM3lw7H7kdNK6+2u0GSybktoMMIwof+SjexZxsYcnUtQ3/AUlstKdWMOQov0oBJkZQn6BdLnk/Wmeuqud2dO91bPmxqK/nXOwgzH/Qj2izqkEUmwhA4FUbODfJwvZcFScxyiJzSeB8jY2mofuTazoXz4o6MsE0OtLm/pJ3GX22grO1+KA7zFXsqrA2x61SZAvkNRQ+4u0pGM5zyWPVTEI3uyXHjrUPn/ss4AtkxnZzUH6Y2ag6xnXqs4PuPANtPuVW38IL6HYtaYTzVuI6vyCuQRsdp/pxwPCsgVRX+h69d44u9hrW36y4WVT2F7/ri3PjeZT9ehKd9zsZsAaei6kTXvLh5EOrvkelHSG8qhHyYDHnqZYMZ/QXF8ePIDi3iTNcd6Jssdqqm6VLXKpDrpUjgmPIGc3WOFR58hkMElZ43yZB6/6K/d+0I3zluyFZBBVko9XvU6l7M0OugfwkCd0oY/62DfHMcaGQu1Hz+SVNbc3JjTTReb00uk2JMrpFxBvxMa4lsN6GsNgrlMKE0qjWFLbBXtSICJ+echEA=
  on:
    tags: true
    branch: master
  skip_cleanup: true
install:
  - pip install unittest2
script:
    - echo "TODO"