[project]
name = "iyzipay"
version = "1.0.46"
dynamic = ["classifiers"]
description = "iyzipay api python client"
readme = { file = "README.md", content-type = "text/markdown" }
license = {text = "MIT"}
authors = [{name = "iyzico"}]
